# Generated by Django 5.1.1 on 2024-09-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя категории', max_length=100, verbose_name='Имя категории')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Имя продукта', max_length=100, verbose_name='Имя продукта')),
                ('description', models.TextField(help_text='Введите Описание продукта', verbose_name='Описание продукта')),
                ('image', models.ImageField(help_text='Загрузите изображение товара', upload_to='index/images', verbose_name='Изображение товара')),
                ('price', models.IntegerField(help_text='Введите цену', verbose_name='Цена товара')),
                ('category', models.ForeignKey(blank=True, help_text='Введите название категории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='index.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
