# Generated by Django 5.1.1 on 2024-09-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_specialoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffers',
            name='discounted_price',
            field=models.IntegerField(help_text='Введите цену', verbose_name='Цена товара'),
        ),
    ]
