# Generated by Django 5.1.1 on 2024-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_specialoffers_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffers',
            name='discounted_price',
            field=models.IntegerField(help_text='Введите цену', verbose_name='Цена товара со скидкой'),
        ),
    ]
