# Generated by Django 5.1.1 on 2024-09-18 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_specialoffers_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Введите дату создания', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
